version: '3'

services:
  mvp:
    container_name: mvp_app
    build: .
    depends_on:
      - 'database'
    ports:
      - '3000:3000'
    volumes:
      - ./:/app

  database:
    container_name: mvp_db
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=mvp
      - MYSQL_ROOT_PASSWORD=student      